# Generated by Django 4.0 on 2024-04-25 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_alter_evaluateinstelemetrydata_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpTimesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.BigIntegerField(editable=False)),
                ('function_name', models.TextField(editable=False)),
                ('elapsed_time', models.IntegerField(editable=False)),
                ('session_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='up_times', to='telemetry.trainingsession')),
            ],
        ),
    ]
